//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVXK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETVEXE
    {
        public string MaVeXe { get; set; }
        public string ViTriGhe { get; set; }
        public string DiemDon { get; set; }
        public string DiemTra { get; set; }
        public System.DateTime NgayXuat { get; set; }
    
        public virtual VEXE VEXE { get; set; }
    }
}
