//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVXK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENXE()
        {
            this.PHANCONG_TAIXE_CHUYENXE = new HashSet<PHANCONG_TAIXE_CHUYENXE>();
            this.VEXEs = new HashSet<VEXE>();
        }
    
        public string MaChuyenXe { get; set; }
        public string MaTuyenXe { get; set; }
        public string MaXe { get; set; }
        public double GiaTien { get; set; }
        public Nullable<int> SoGheTrong { get; set; }
        public Nullable<System.TimeSpan> GioKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.TimeSpan> GioDenDuKien { get; set; }
        public Nullable<System.DateTime> NgayDenDuKien { get; set; }
    
        public virtual TUYENXE TUYENXE { get; set; }
        public virtual XE XE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG_TAIXE_CHUYENXE> PHANCONG_TAIXE_CHUYENXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEXE> VEXEs { get; set; }
    }
}
