//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVXK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBanVeXeKhachEntities1 : DbContext
    {
        public QLBanVeXeKhachEntities1()
            : base("name=QLBanVeXeKhachEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUYENXE> CHUYENXEs { get; set; }
        public virtual DbSet<HANHKHACH> HANHKHACHes { get; set; }
        public virtual DbSet<LOAIXE> LOAIXEs { get; set; }
        public virtual DbSet<PHANCONG_TAIXE_CHUYENXE> PHANCONG_TAIXE_CHUYENXE { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TAIXE> TAIXEs { get; set; }
        public virtual DbSet<TINHTHANH> TINHTHANHs { get; set; }
        public virtual DbSet<TUYENXE> TUYENXEs { get; set; }
        public virtual DbSet<VEXE> VEXEs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
        public virtual DbSet<CHITIETVEXE> CHITIETVEXEs { get; set; }
    
        [DbFunction("QLBanVeXeKhachEntities1", "fn_HienThiChiTietVe")]
        public virtual IQueryable<fn_HienThiChiTietVe_Result> fn_HienThiChiTietVe(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_HienThiChiTietVe_Result>("[QLBanVeXeKhachEntities1].[fn_HienThiChiTietVe](@UserID)", userIDParameter);
        }
    
        [DbFunction("QLBanVeXeKhachEntities1", "fn_HienThiChiTietVeLoc")]
        public virtual IQueryable<fn_HienThiChiTietVeLoc_Result> fn_HienThiChiTietVeLoc(string userID, string maVeXe, Nullable<System.DateTime> ngayKhoiHanh, string diemDi, string diemDen, string trangThai)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var maVeXeParameter = maVeXe != null ?
                new ObjectParameter("MaVeXe", maVeXe) :
                new ObjectParameter("MaVeXe", typeof(string));
    
            var ngayKhoiHanhParameter = ngayKhoiHanh.HasValue ?
                new ObjectParameter("NgayKhoiHanh", ngayKhoiHanh) :
                new ObjectParameter("NgayKhoiHanh", typeof(System.DateTime));
    
            var diemDiParameter = diemDi != null ?
                new ObjectParameter("DiemDi", diemDi) :
                new ObjectParameter("DiemDi", typeof(string));
    
            var diemDenParameter = diemDen != null ?
                new ObjectParameter("DiemDen", diemDen) :
                new ObjectParameter("DiemDen", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_HienThiChiTietVeLoc_Result>("[QLBanVeXeKhachEntities1].[fn_HienThiChiTietVeLoc](@UserID, @MaVeXe, @NgayKhoiHanh, @DiemDi, @DiemDen, @TrangThai)", userIDParameter, maVeXeParameter, ngayKhoiHanhParameter, diemDiParameter, diemDenParameter, trangThaiParameter);
        }
    
        [DbFunction("QLBanVeXeKhachEntities1", "fn_HienThiChuyenXe")]
        public virtual IQueryable<fn_HienThiChuyenXe_Result> fn_HienThiChuyenXe(string diemDi, string diemDen, Nullable<System.DateTime> ngayKhoiHanh)
        {
            var diemDiParameter = diemDi != null ?
                new ObjectParameter("DiemDi", diemDi) :
                new ObjectParameter("DiemDi", typeof(string));
    
            var diemDenParameter = diemDen != null ?
                new ObjectParameter("DiemDen", diemDen) :
                new ObjectParameter("DiemDen", typeof(string));
    
            var ngayKhoiHanhParameter = ngayKhoiHanh.HasValue ?
                new ObjectParameter("NgayKhoiHanh", ngayKhoiHanh) :
                new ObjectParameter("NgayKhoiHanh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_HienThiChuyenXe_Result>("[QLBanVeXeKhachEntities1].[fn_HienThiChuyenXe](@DiemDi, @DiemDen, @NgayKhoiHanh)", diemDiParameter, diemDenParameter, ngayKhoiHanhParameter);
        }
    
        [DbFunction("QLBanVeXeKhachEntities1", "fn_HienThiTatCaChuyenXe")]
        public virtual IQueryable<fn_HienThiTatCaChuyenXe_Result> fn_HienThiTatCaChuyenXe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_HienThiTatCaChuyenXe_Result>("[QLBanVeXeKhachEntities1].[fn_HienThiTatCaChuyenXe]()");
        }
    
        public virtual int HienThiThongTinGhe(string maChuyenXe)
        {
            var maChuyenXeParameter = maChuyenXe != null ?
                new ObjectParameter("MaChuyenXe", maChuyenXe) :
                new ObjectParameter("MaChuyenXe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HienThiThongTinGhe", maChuyenXeParameter);
        }
    
        public virtual int sp_CapNhatSoGheTrong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatSoGheTrong");
        }
    
        public virtual int sp_DatVe(string maHanhKhach, string maChuyenXe, string viTriGhe)
        {
            var maHanhKhachParameter = maHanhKhach != null ?
                new ObjectParameter("MaHanhKhach", maHanhKhach) :
                new ObjectParameter("MaHanhKhach", typeof(string));
    
            var maChuyenXeParameter = maChuyenXe != null ?
                new ObjectParameter("MaChuyenXe", maChuyenXe) :
                new ObjectParameter("MaChuyenXe", typeof(string));
    
            var viTriGheParameter = viTriGhe != null ?
                new ObjectParameter("ViTriGhe", viTriGhe) :
                new ObjectParameter("ViTriGhe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DatVe", maHanhKhachParameter, maChuyenXeParameter, viTriGheParameter);
        }
    
        public virtual ObjectResult<sp_HienThiChuyenXe_Result> sp_HienThiChuyenXe(string diemDi, string diemDen, Nullable<System.DateTime> ngayKhoiHanh)
        {
            var diemDiParameter = diemDi != null ?
                new ObjectParameter("DiemDi", diemDi) :
                new ObjectParameter("DiemDi", typeof(string));
    
            var diemDenParameter = diemDen != null ?
                new ObjectParameter("DiemDen", diemDen) :
                new ObjectParameter("DiemDen", typeof(string));
    
            var ngayKhoiHanhParameter = ngayKhoiHanh.HasValue ?
                new ObjectParameter("NgayKhoiHanh", ngayKhoiHanh) :
                new ObjectParameter("NgayKhoiHanh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiChuyenXe_Result>("sp_HienThiChuyenXe", diemDiParameter, diemDenParameter, ngayKhoiHanhParameter);
        }
    
        public virtual int sp_InsertChuyenXe(string maTuyenXe, string maXe, Nullable<double> giaTien, Nullable<System.TimeSpan> gioKhoiHanh, Nullable<System.DateTime> ngayKhoiHanh, Nullable<System.TimeSpan> gioDenDuKien, Nullable<System.DateTime> ngayDenDuKien)
        {
            var maTuyenXeParameter = maTuyenXe != null ?
                new ObjectParameter("MaTuyenXe", maTuyenXe) :
                new ObjectParameter("MaTuyenXe", typeof(string));
    
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(double));
    
            var gioKhoiHanhParameter = gioKhoiHanh.HasValue ?
                new ObjectParameter("GioKhoiHanh", gioKhoiHanh) :
                new ObjectParameter("GioKhoiHanh", typeof(System.TimeSpan));
    
            var ngayKhoiHanhParameter = ngayKhoiHanh.HasValue ?
                new ObjectParameter("NgayKhoiHanh", ngayKhoiHanh) :
                new ObjectParameter("NgayKhoiHanh", typeof(System.DateTime));
    
            var gioDenDuKienParameter = gioDenDuKien.HasValue ?
                new ObjectParameter("GioDenDuKien", gioDenDuKien) :
                new ObjectParameter("GioDenDuKien", typeof(System.TimeSpan));
    
            var ngayDenDuKienParameter = ngayDenDuKien.HasValue ?
                new ObjectParameter("NgayDenDuKien", ngayDenDuKien) :
                new ObjectParameter("NgayDenDuKien", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertChuyenXe", maTuyenXeParameter, maXeParameter, giaTienParameter, gioKhoiHanhParameter, ngayKhoiHanhParameter, gioDenDuKienParameter, ngayDenDuKienParameter);
        }
    
        public virtual int sp_TaoTaiKhoan(string hoTen, string soDienThoai, string email, string pass)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoTaiKhoan", hoTenParameter, soDienThoaiParameter, emailParameter, passParameter);
        }
    
        public virtual int SP_ThemChuyenXe(string maXe, string maTaiXe, string tenTuyenXe, string tenDiemDi, string tenDiemDen, Nullable<System.DateTime> ngayKhoiHanh, Nullable<System.TimeSpan> gioKhoiHanh, Nullable<System.DateTime> ngayDenDuKien, Nullable<System.TimeSpan> gioDenDuKien, Nullable<double> giaVe)
        {
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            var maTaiXeParameter = maTaiXe != null ?
                new ObjectParameter("MaTaiXe", maTaiXe) :
                new ObjectParameter("MaTaiXe", typeof(string));
    
            var tenTuyenXeParameter = tenTuyenXe != null ?
                new ObjectParameter("TenTuyenXe", tenTuyenXe) :
                new ObjectParameter("TenTuyenXe", typeof(string));
    
            var tenDiemDiParameter = tenDiemDi != null ?
                new ObjectParameter("TenDiemDi", tenDiemDi) :
                new ObjectParameter("TenDiemDi", typeof(string));
    
            var tenDiemDenParameter = tenDiemDen != null ?
                new ObjectParameter("TenDiemDen", tenDiemDen) :
                new ObjectParameter("TenDiemDen", typeof(string));
    
            var ngayKhoiHanhParameter = ngayKhoiHanh.HasValue ?
                new ObjectParameter("NgayKhoiHanh", ngayKhoiHanh) :
                new ObjectParameter("NgayKhoiHanh", typeof(System.DateTime));
    
            var gioKhoiHanhParameter = gioKhoiHanh.HasValue ?
                new ObjectParameter("GioKhoiHanh", gioKhoiHanh) :
                new ObjectParameter("GioKhoiHanh", typeof(System.TimeSpan));
    
            var ngayDenDuKienParameter = ngayDenDuKien.HasValue ?
                new ObjectParameter("NgayDenDuKien", ngayDenDuKien) :
                new ObjectParameter("NgayDenDuKien", typeof(System.DateTime));
    
            var gioDenDuKienParameter = gioDenDuKien.HasValue ?
                new ObjectParameter("GioDenDuKien", gioDenDuKien) :
                new ObjectParameter("GioDenDuKien", typeof(System.TimeSpan));
    
            var giaVeParameter = giaVe.HasValue ?
                new ObjectParameter("GiaVe", giaVe) :
                new ObjectParameter("GiaVe", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemChuyenXe", maXeParameter, maTaiXeParameter, tenTuyenXeParameter, tenDiemDiParameter, tenDiemDenParameter, ngayKhoiHanhParameter, gioKhoiHanhParameter, ngayDenDuKienParameter, gioDenDuKienParameter, giaVeParameter);
        }
    
        public virtual int sp_ThemHanhKhach(string soDienThoai, string tenHanhKhach, string gioiTinh, string diaChi, string email)
        {
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var tenHanhKhachParameter = tenHanhKhach != null ?
                new ObjectParameter("TenHanhKhach", tenHanhKhach) :
                new ObjectParameter("TenHanhKhach", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemHanhKhach", soDienThoaiParameter, tenHanhKhachParameter, gioiTinhParameter, diaChiParameter, emailParameter);
        }
    
        public virtual int sp_ThongKeChuyenXeMuaNhieuNhatTheoThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKeChuyenXeMuaNhieuNhatTheoThang");
        }
    
        public virtual int sp_ThongKeDoanhThuTong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKeDoanhThuTong");
        }
    
        public virtual int sp_ThongKeTop5ChuyenXeTheoThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKeTop5ChuyenXeTheoThang");
        }
    
        public virtual ObjectResult<SP_TIMCHUYENXE_Result> SP_TIMCHUYENXE(string diemDi, string diemDen, Nullable<System.DateTime> ngayDi, Nullable<System.DateTime> ngayVe)
        {
            var diemDiParameter = diemDi != null ?
                new ObjectParameter("DiemDi", diemDi) :
                new ObjectParameter("DiemDi", typeof(string));
    
            var diemDenParameter = diemDen != null ?
                new ObjectParameter("DiemDen", diemDen) :
                new ObjectParameter("DiemDen", typeof(string));
    
            var ngayDiParameter = ngayDi.HasValue ?
                new ObjectParameter("NgayDi", ngayDi) :
                new ObjectParameter("NgayDi", typeof(System.DateTime));
    
            var ngayVeParameter = ngayVe.HasValue ?
                new ObjectParameter("NgayVe", ngayVe) :
                new ObjectParameter("NgayVe", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TIMCHUYENXE_Result>("SP_TIMCHUYENXE", diemDiParameter, diemDenParameter, ngayDiParameter, ngayVeParameter);
        }
    
        public virtual int sp_TinhTongSoLuongVeTheoNam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhTongSoLuongVeTheoNam");
        }
    
        public virtual ObjectResult<SP_XemVeXe_Result> SP_XemVeXe(string maHanhKhach)
        {
            var maHanhKhachParameter = maHanhKhach != null ?
                new ObjectParameter("MaHanhKhach", maHanhKhach) :
                new ObjectParameter("MaHanhKhach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemVeXe_Result>("SP_XemVeXe", maHanhKhachParameter);
        }
    
        public virtual int sp_XoaChuyenXe(string maChuyenXe)
        {
            var maChuyenXeParameter = maChuyenXe != null ?
                new ObjectParameter("MaChuyenXe", maChuyenXe) :
                new ObjectParameter("MaChuyenXe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChuyenXe", maChuyenXeParameter);
        }
    
        public virtual int sp_XoaHanhKhach(string maHanhKhach)
        {
            var maHanhKhachParameter = maHanhKhach != null ?
                new ObjectParameter("MaHanhKhach", maHanhKhach) :
                new ObjectParameter("MaHanhKhach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaHanhKhach", maHanhKhachParameter);
        }
    
        public virtual int them_taixe(string maXe, string tenTaiXe, string soDienThoai, string cCCD, string diaChi)
        {
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            var tenTaiXeParameter = tenTaiXe != null ?
                new ObjectParameter("TenTaiXe", tenTaiXe) :
                new ObjectParameter("TenTaiXe", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_taixe", maXeParameter, tenTaiXeParameter, soDienThoaiParameter, cCCDParameter, diaChiParameter);
        }
    
        public virtual ObjectResult<string> XoaTaiKhoan(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("XoaTaiKhoan", userIDParameter);
        }
    
        public virtual int XoaTaiXeVaPhanCong(string maTaiXe)
        {
            var maTaiXeParameter = maTaiXe != null ?
                new ObjectParameter("MaTaiXe", maTaiXe) :
                new ObjectParameter("MaTaiXe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaTaiXeVaPhanCong", maTaiXeParameter);
        }
    }
}
