//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVXK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG_TAIXE_CHUYENXE
    {
        public string MaTaiXe { get; set; }
        public string MaChuyenXe { get; set; }
        public string PhuTrach { get; set; }
    
        public virtual CHUYENXE CHUYENXE { get; set; }
    }
}
