//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVXK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIXE
    {
        public string MaTaiXe { get; set; }
        public string MaXe { get; set; }
        public string TenTaiXe { get; set; }
        public string SoDienThoai { get; set; }
        public string CCCD { get; set; }
        public string DiaChi { get; set; }
    
        public virtual XE XE { get; set; }
    }
}
