//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVXK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEXE()
        {
            this.CHITIETVEXEs = new HashSet<CHITIETVEXE>();
        }
    
        public string MaVeXe { get; set; }
        public string MaHanhKhach { get; set; }
        public string MaChuyenXe { get; set; }
        public string ViTriGhe { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
    
        public virtual CHUYENXE CHUYENXE { get; set; }
        public virtual HANHKHACH HANHKHACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETVEXE> CHITIETVEXEs { get; set; }
    }
}
